export const INNO_MAIN_COLOR = '#0F3A50'
export const INNO_SECONDARY_COLOR = '#38a09d'
export const INNO_SECONDARY_COLOR_HOVER = '#248f8c'
export const INNO_MAIN_COLOR_FADED = '#2b6887'
export const INNO_MAIN_TEXT_COLOR = 'white'
export const HEADER_COLOR = 'white'
