export const HEADER_HEIGHT = '40px'

export const FLAGS_HEIGHT = '36px'

/* NEWS */
export const SLIDER_FAKE_PADDING_VERTICAL_ABS = 40
export const SLIDER_FAKE_PADDING_HORIZONTAL_ABS = 10
export const SLIDER_FAKE_PADDING_VERTICAL = `${SLIDER_FAKE_PADDING_VERTICAL_ABS}px`
export const SLIDER_FAKE_PADDING_HORIZONTAL = `${SLIDER_FAKE_PADDING_HORIZONTAL_ABS}px`
export const FADED_DIV_WIDTH = '30px'

/* FILTER */
export const SIDEBAR_WIDTH = '250px'
